trigger:
- master

pool:
  name: 'Local'

name: '$(majorMinorVersion).$(semanticVersion)' 

variables:
  buildConfiguration: 'Release'
  majorMinorVersion: 0.1.0
  semanticVersion: $[counter(variables['majorMinorVersion'], 0)]
  buildVersion: '$(majorMinorVersion).$(semanticVersion)'

steps:
#Säkerställ att rätt NET Core SDK finns
- task: UseDotNet@2
  displayName: 'Use .Net Core sdk 3.1.x'
  inputs:
    packageType: 'sdk'
    version: '5.0.x'

#Kompilera hela repot
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) -p:Version=$(buildVersion)'

#Kör eventuella unittester
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.UnitTests.csproj'
    arguments: '--configuration $(buildConfiguration) -p:Version=$(buildVersion)'
    testRunTitle: 'Unittests $(Build.DefinitionName)_$(buildVersion)'

#Om bygget innehåller Nuget paket så kopiera dessa till ArtifactStagingDirectory
- task: CopyFiles@2
  inputs:
    Contents: '**/bin/$(buildConfiguration)/**/*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    flattenFolders: true

#Om bygget innehåller Nuget paket så pusha dessa till nuget feed
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '738eaab2-7fa4-48f8-9a04-a44cd8830cf9/f23b5e21-2094-4cf5-829c-51e3752ec779'

#Om något kopierats till ArtifactStagingDirectory så publicera även detta till droplocation
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
